name: Generate Ascii Art
on: push
jobs:
  ascii_art-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install cowsay
        run: sudo apt-get install cowsay -y

      - name: Generate Dragon art
        run: cowsay -f dragon "dragon exists!">> dragon.txt

      - name: test dragon existence
        run: grep -i "dragon" dragon.txt

      - name: Read File
        run: cat dragon.txt

      - name: List Repo files
        run: ls -a
