name: Generate Ascii Art
on: push
jobs:
  ascii_art-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List Repo files
        run: ls -ltra

      - name: Extecute script-1.sh
        run: |
          chmod +x ./script-1.sh
          ./script-1.sh
